### ISSUE TITLE
rasa test widget page does not exists

### ISSUE THREAD

**Issue by programmeddeath1** [chatwoot/implementation-examples#8]
Im running the rasa implementation-example locally. The http://localhost:3000/test_widgets page gives the following error

```The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.
```
Which logs will give information about this error? I assumed this test screen would work in local environment

**Comment by sojan-official** [comment]
the URL is:  http://localhost:3000/widget_tests

**Comment by programmeddeath1** [comment]
Its the same with that url too

![image](https://user-images.githubusercontent.com/44861370/187854228-03836457-301d-44ca-a869-be3ab1c46cad.png)

**Comment by sojan-official** [comment]
@programmeddeath1  the URL is accessible only if your RAILS_ENV is set to development. So please double-check that.
